config/routes.rb
Bookies::Application.routes.draw do
  # root of site, set to bookmarks index page
  root :to => 'bookmarks#index'

  # resources creates CRUD routes for these models
  resources :users, :bookmarks, :sessions, :identities

  # for omniauth
  post 'auth/:provider/callback', to: 'sessions#create'
  # had to hardcode identity route in rails 4
  post 'auth/identity/callback', to: 'sessions#create'
  # auth/../callback is post only 
  get 'auth/:provider/callback', to: 'sessions#create'
  # match 'auth/failure', to: redirect('/')
  match 'auth/failure' => 'sessions#new', :notice => "Email or password incorrect", via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "register" => "users#new", :as => "register"
  get "signup" => "users#new", :as => "signup"
  get "user/regenerate_token" => "users#regenerate_token"

  get "my_bookmarks" => "bookmarks#user_bookmarks", :as => "my_bookmarks"

  get "search" => "search#index"

  get "tags/" => "tags#index", :as => "tags"
  # show stream of bookmarks for specific tag
  get "tags/name/:name" => "bookmarks#tag", :as => "tags_name"
  # show Most popular tags of user
  get "tags/user/:id" => "tags#user", :as => "tags_user"

  get "bookmarks/:id/delete" => 'bookmarks#destroy', :as => "delete_bookmark"
  get "bookmarks/user/:id" => "bookmarks#user"
  # show archive of URL if it exists
  get "bookmarks/archive/:id" => "bookmarks#archive", :as => "archive_bookmark"
  get "user/:id/bookmarks" => "bookmarks#user"
  get "bookmarklet" => "bookmarks#bookmarklet"
  get "bookmarklet/success" => "bookmarks#success"

  # for delicious API v1
  get "api/posts/all" => "api#posts_all"
  get "api/posts/all/:tag" => "api#posts_all"
  get "api/posts/:id" => "api#index"
  get "api/upload"   => "api#upload"
  post "api/import"   => "api#import"
  post "api/posts/add"   => "api#posts_add"

  mount Resque::Server, :at => "/resque-web"
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  before_save :hash_url
  belongs_to :user
  has_one :archive
  acts_as_taggable

  validates_presence_of :url, :title, :user_id

  # Set default order: most recently updated
  default_scope { order('updated_at DESC') }
  scope :published, -> { where(private: :nil) }
  scope :my_bookmarks, ->(user_id) { where(user_id: user_id) }
  # scope :published_or_mine,->(user_id) find_by_sql(.. UNION ..)
  scope :unpublished, -> { where(private: true) }
  scope :archived, -> { where(is_archived: true) }

  # download and archive the bookmark
  def archive_the_url
    if is_archived?
      logger.info "Queued the archiving of the url with id: #{id}"
      Resque.enqueue(BookmarkArchiver, id)
    end
  end
  private
 
  def hash_url
    self.hashed_url = Digest::MD5.hexdigest(url)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :require_login, only: [:update, :edit]
  before_action :set_bookmark, only: [:show, :edit, :update, :archive, :destroy]
  respond_to :html

  # GET /bookmarks.xml
  def index
    @bookmarks = Bookmark.all.page(params[:page])
  end
  
  # GET /bookmarks/new
  # GET /bookmarks/new.xml
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/:id
  def show
  end

  # get /bookmarks/:id/edit
  def edit
    if session[:user_id] == @bookmark.user_id
      respond_with @bookmark
    else 
      flash[:error] = "Sorry, you do not have permissions to edit Bookmark!"
      redirect_to root_url
    end
  end
 
  # POST /bookmarks
  def create
    @bookmark = Bookmark.find_or_initialize_by(:user_id => params[:bookmark][:user_id], :url => params[:bookmark][:url] )
    @bookmark.update(bookmark_params)
    if @bookmark.save
      # call the archive method here only
      @bookmark.archive_the_url
      redirect_to(@bookmark, :notice => 'Bookmark was successfully created.', :locals => {:close_window => params[:bookmark][:is_popup]})
      # if params[:bookmark][:is_popup]
      #   redirect_to(@bookmark, :notice => 'Close the Window!', :locals => {:close_window => 1})
      # else  
      #   redirect_to(@bookmark, :notice => 'Bookmark was successfully created.')
      # end
    else
      flash[:warning] = "There was a problem saving that bookmark."
      render :action => "new" 
    end
  end

  def update
    # check if user has permission to edit bookmark
    if session[:user_id] != @bookmark.user_id
      flash[:error] = "Sorry, you do not have permission to edit another user's bookmarks!"
      redirect_to root_url
    end
    # warning: update_attributes side-steps validation
    if @bookmark.update(bookmark_params)
      # call the archive method here only
      @bookmark.archive_the_url
      flash[:notice] = "\"#{@bookmark.title}\" was successfully updated."
      if params[:bookmark][:is_popup]
        redirect_to(@bookmark, :notice => 'Close the Window!', :locals => {:close_window => 1})
      else  
        redirect_to(@bookmark, :notice => 'Bookmark was successfully created.')
      end
    else 
      flash[:notice] = "Unable to update bookmark."
      redirect_to root_url
    end
  end

  # GET /bookmarks/user/:id
  def user
    @user = User.find(params[:id])
    # FIXME TODO
    if current_user && current_user.id.to_s == params[:id] 
      @bookmarks = Bookmark.where(user_id: params[:id]).page(params[:page]).per_page(20)
    else
      @bookmarks = Bookmark.where(user_id: params[:id]).where(private: nil).page(params[:page]).per_page(19)
    end
  end

  def user_bookmarks
    @bookmarks = Bookmark.where(:user_id => current_user.id)
  end

  # GET /bookmark/archive/1
  def archive
    render layout: "archive"
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    if session[:user_id] != @bookmark.user_id
      flash[:error] = "Sorry, you do not have permission to delete this bookmark."
      redirect_to root_url
    else 
      @bookmark.archive.destroy if @bookmark.archive
      # @bookmark.archive.try(:destroy)
      @bookmark.destroy
      redirect_to root_url, :notice => "#{@bookmark.title} was deleted!"
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.xml
  def bookmarklet
    unless session[:user_id] 
      flash[:info] = "Please Sign In."
      session[:return_to] = request.fullpath
      redirect_to login_url
    end
    @bookmark = Bookmark.find_or_create_by(:url => params[:address], :user_id => session[:user_id])
  end

  def tag
    @bookmarks = Bookmark.tagged_with(params[:name]).page(params[:page]) 
    @name = params[:name]
  end

  private
  def require_login
    unless session[:user_id]
      flash[:info] = "Please Sign In."
      redirect_to login_url
    end
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bookmark_params
    params.require(:bookmark).permit(:url, :title, :private, :desc, :is_archived, :tag_list)
  end
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
  include ActsAsTaggableOn::TagsHelper
  def add_bookmark(href, desc, extended, tags, time, hashed_url )
    @Bookmark = Bookmark.new
    @Bookmark.user_id = session[:user_id]
    @Bookmark.url = href
    @Bookmark.title = desc
    @Bookmark.created_at = Time.now
    @Bookmark.hashed_url = Digest::MD5.hexdigest(href)
    @Bookmark.save
  end

  def bookmark_archive_link(b)
    if /html/.match(b.archive_url)
      archive_bookmark_path(b)
    else
      b.archive_url
    end
  end
end

app/views/bookmarks/_bookmark.html.erb
 <div class="bookmark-wrapper<%= b.private ? " private" :"" %>">
    <div class="bookmark-title"><a href="<%= b.url %>"><%= b.title %></a></div>
    <div class="bookmark-desc">
      <%= b.desc %>
    </div>
    <div class="bookmark-tags">
      <% b.tag_list.each do |t| %>
        <a href="/tags/name/<%= t %>"><%= t %></a>
      <% end %>
    </div>
    <div class="bookmark-details">
      <% if b.updated_at != b.created_at %>
        <span class="bookmark-updated">Updated: <%= nice_date_form(b.updated_at) %></span>
        <span class="bookmark-created">Created: <%= nice_date_form(b.created_at) %></span>
      <% else %>
        <span class="bookmark-created"><%= nice_date_form(b.created_at) %></span>
      <% end %>
      <span class="bookmark-owner">by <a href="users/<%= b.user_id %>"><%= b.user.username %></a>
      <% if b.user_id == session[:user_id] %>
        <span class="bookmark-ops">
          <span class="bookmark-edit"> <%= link_to "Edit", edit_bookmark_path(b) %> </span>
          <span class="bookmark-delete"><%= link_to("Delete", b, :method => 'Delete', data: {:confirm => "Are you sure you want to delete that?"}) %></span>
          <% if b.is_archived? %>
            <span class="bookmark-archive"><%= link_to "View Archive", bookmark_archive_link(b) %></span>
          <% end %>
        </span>
      <% end %>
      </span>
    </div>
 </div>

app/views/bookmarks/_form.html.erb
<%= form_for @bookmark, html: { class: "form"} do |f| %>
  
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :url, :size => 60, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :size => 60, class: "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :desc, "Description" %>
    <%= f.text_area :desc, rows: 4, :size => 60, class: "form-control" %>
  </div>
  
  <div class="form-group field_tags">
    <%= f.label :tag_list, "Tags" %>
    <%= f.text_field :tag_list, :value => @bookmark.tag_list.to_s, :size => 60, class: "form-control" %>
  </div>
  
  <div class="form-group field">
		<%= f.label :private %>
		<%= f.check_box :private %>
  </div>
  
  <div class="form-group field">
    <%= f.label(:is_archived, 'archive url?') %>
    <%= f.check_box :is_archived %>
  </div>

  <%= f.hidden_field :user_id, :value => session[:user_id] %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/archive.html.erb
<div class="archive-main">
<% 
# archive_file = @bookmark.archive_url
archive_file = "public/archive/#{@bookmark.id}.html"
if File.exists? archive_file then 
  content = File.open( archive_file ).read
%>
  <%= raw content %>
<%
else 
%>
  <%= "No archive saved" %>
<%
end
%>
</div>

app/views/bookmarks/bookmarklet.html.erb
<div class="bookmarklet">
<script type="text/javascript">
$(function() {
  $('#bookmark_tags').focus();
});
</script>
 
<%= form_for @bookmark, html: { class: "form"} do |f| %>
  
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :url, :size => 60, :value => params[:address], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :size => 60, :value => params[:title], class: "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :desc, "Description" %>
    <%= f.text_field :desc, :size => 60, :value => params[:description], class: "form-control" %>
  </div>
  
  <div class="form-group field_tags">
    <%= f.label :tag_list, "Tags" %>
    <%= f.text_field :tag_list, :value => @bookmark.tag_list.to_s, :size => 60, class: "form-control" %>
  </div>
  
  <div class="form-group field">
		<%= f.label :private %>
		<%= f.check_box :private %>
  </div>
  
  <div class="form-group field">
    <%= f.label(:is_archived, 'Archive Page') %>
    <%= f.check_box :is_archived %>
  </div>

  <%= f.hidden_field :user_id, :value => session[:user_id] %>
  <%= f.hidden_field :is_popup, :value => 1 %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>


<%= render 'form' %>

app/views/bookmarks/index.html.erb
<% content_for :head, auto_discovery_link_tag(:rss, bookmarks_url(format: "rss")) %>

<h2>Welcome <%= session[:username] ? session[:username] : "Visitor" %> </h2>

<p />
<div class="main-wrapper">

<%
  @bookmarks.each do |b|
    # this will make the number of bookmarks on page less than expected amount
    next if b.private == true and b.user_id != session[:user_id]
%>
  <%= render partial: 'bookmark', locals: { b: b} %>
<%
  end
%>


<div class="flickr_pagination">
  <div clas="page_info">
    <%= page_entries_info @bookmarks %>
  </div>
  <%= will_paginate @bookmarks, :container => false %>
</div>


</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.title %></h1>

<script type="text/javascript">
  $(function() {
    if (window.name == "Bkmark.me Bookmarks") {
      window.close();
    }
  });
</script>


<div class="messages-wrapper">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
</div>


<div class=bookmark-desc>
  <a href="<%= @bookmark.url %>"><%= @bookmark.title %></a>
</div>
<div class=bookmark-details>
  <div class=bookmark-desc>
    <pre><%= @bookmark.desc %></pre>
  </div>
  <div class=bookmark-tags>
    tags:  <%= @bookmark.tag_list.to_a.join(", ") %>
  </div>
  <% if @bookmark.is_archived? %>
    <div class=bookmark-archive>
      <a href="/archive/<%= @bookmark.id %>.html">View Archive</a>
    </div>
  <% end %>

</div>

app/views/bookmarks/tag.html.erb
<h2>Tagged: <%= @name %></h2>
<p />
<div class="main-wrapper">

<%
  @bookmarks.each do |b|
    # this will make the number of bookmarks on page less than expected amount
    next if b.private == true and b.user_id != session[:user_id]
%>
  <%= render partial: 'bookmark', locals: { b: b} %>
<%
  end
%>


<div class="flickr_pagination">
  <div clas="page_info">
    <%= page_entries_info @bookmarks %>
  </div>
  <%= will_paginate @bookmarks, :container => false %>
</div>


</div>

app/views/bookmarks/user.html.erb
<h2><%= @user.username.capitalize %>'s Bookmarks </h2>

<div class="messages-wrapper">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
</div>


<p />
<div class="main-wrapper">

 <% 
  @bookmarks.each do |b|
 %>
 <div class="bookmark-wrapper<%= b.private ? " private" :"" %>">
  <div class="bookmark-title"><a href="<%= b.url %>"><%= b.title %></a></div>
  <div class="bookmark-desc">
    <%= b.desc %>
  </div>
  <div class="bookmark-tags">
    <% b.tags.each do |t| %>
      <a href="/tags/name/<%= t.name %>"><%= t.name %></a>

    <% end %>
  </div>

  <div class="bookmark-details"> 
    <span class="bookmark-created"><%= nice_date_form(b.created_at) %></span>
  <% if session[:user_id] == b.user_id %>
      <span class="bookmark-ops">
        <span class="bookmark-edit"> <%= link_to "Edit", edit_bookmark_path(b) %> </span>
        <span class="bookmark-delete"><a href="/bookmarks/<%= b.id %>/delete">Delete</a></span>
      </span>
    </span>
  <% end %>
  </div>

 </div>
 <% 
   end
 %>

<div class="flickr_pagination">
  <div clas="page_info">
    <%= page_entries_info @posts %>
  </div>
  <%= will_paginate @posts, :container => false %>
</div>


</div>

app/views/bookmarks/user_bookmarks.html.erb
<h2>Welcome <%= session[:username] %> </h2>

<div class="messages-wrapper">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
</div>


<p />
<div class="main-wrapper">

 <% 
  @bookmarks.each do |b|
     tags=[] 
     b.tags.each do |t| 
       tags << t.name
     end
 %>
 <div class="bookmark-wrapper">
  <div class="bookmark-title"><a href="<%= b.url %>"><%= b.title %></a></div>
  <div class="bookmark-desc">
    <%= b.desc %>
  </div>
  <div class="bookmark-details">
    <span class="created">Created on: <%= nice_date_form(b.created_at) %></span>
      <span class="bookmark-tags"><span class=tag-name>Tags: </span>
        <%= tags.join(', ') %>
      </span>
    </span>
  </div>
 </div>
 <% 
   end
 %>

</div>